### PR TITLE
Add Homebrew tap support via goreleaser

### PR DESCRIPTION
**Pull request by ahayworth**
A Homebrew tap is a third-party git repo that contains a "formula" that
homebrew can use to install some software not included in homebrew core.
The repo is usually presumed to be on GitHub, and must be named
something like '\<owner\>/homebrew-\<tap name\>' - in our case,
'homebrew-otel-cli'.

It seems that goreleaser supports automatically creating a formula and
then pushing it up to a third-party repo. In order to take advantage of
this support, someone will need to create a repo suitable for hosting
this, and generate the required credentials and pass them to goreleaser
as an env variable (which can be a GitHub secret used in the actions
workflow). Then, when goreleaser runs, it will push the latest formula
to the configured repo and homebrew users can install it.

As an end-user - presuming the repo is 'packethost/homebrew-otel-cli',
you would do something like this:

```
$ brew tap 'packethost/otel-cli'
$ brew install otel-cli
```

Note that while the repo *must* be named 'homebrew-otel-cli', users
drop the 'homebrew-' prefix when adding the tap.

I tested this by running: `goreleaser release --snapshot --skip-publish --rm-dist`
and the following formula was output to `dist/otel-cli.rb`, which looks
correct to me:

```ruby

class OtelCli < Formula
  desc "OpenTelemetry command-line tool for sending events from shell scripts & similar environments"
  homepage "https://github.com/packethost/otel-cli"
  version "v0.0.4-next"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/packethost/otel-cli/releases/download/v0.0.3/otel-cli_v0.0.4-next_Darwin_x86_64.tar.gz"
      sha256 "fe6f51aa4ce8a3cb2e599d455fa36b2f553130fa850ad2fd0ad7ad1657820d1a"
    end
    if Hardware::CPU.arm?
      url "https://github.com/packethost/otel-cli/releases/download/v0.0.3/otel-cli_v0.0.4-next_Darwin_arm64.tar.gz"
      sha256 "e1f9ce6e736d3e9b2346728d83942cdce3277f0dcbc0af72eb992ceb71b6bb56"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/packethost/otel-cli/releases/download/v0.0.3/otel-cli_v0.0.4-next_Linux_x86_64.tar.gz"
      sha256 "23c919ccf087f5f093f87ed14fe57e47deb2d16fb2c0940d9f9d576074be4e18"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/packethost/otel-cli/releases/download/v0.0.3/otel-cli_v0.0.4-next_Linux_arm64.tar.gz"
      sha256 "9d661508f6a0b121a0002ea05c2b361fb8bea14e9e448f76889a29c3d001d470"
    end
  end

  def install
    bin.install "otel-cli"
  end
end
```

### CODE REVIEW

**Comment by ahayworth** [comment]
cc #47

**Comment by ahayworth** [comment]
It should be noted that I didn't actually allow goreleaser to push this up to any repos I own and I'm not 100% certain it would do the right thing if we actually committed this.

**Comment by tobert** [comment]
Ooh, nice, thank you @ahayworth I'll poke at it this afternoon. It shouldn't be a problem for me to get that repo now that we've moved the project over to equinix-labs.

**Comment by tobert** [comment]
@matoszz do you have strong feelings about having a second repo for this to contain the homebrew bits?

**Comment by tobert** [comment]
I've created https://github.com/equinix-labs/homebrew-otel-cli and will mess with this more today/tomorrow.

**Comment by tobert** [comment]
It works!

```
atobey@laptop ~ $ brew tap equinix-labs/otel-cli
==> Tapping equinix-labs/otel-cli
Cloning into '/usr/local/Homebrew/Library/Taps/equinix-labs/homebrew-otel-cli'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (3/3), done.
Tapped 1 formula (12 files, 6.3KB).

atobey@laptop ~ $ brew install otel-cli
==> Installing otel-cli from equinix-labs/otel-cli
==> Downloading https://github.com/equinix-labs/otel-cli/releases/download/v0.0.6-rc2/otel-cli-0.0.6-rc2-Darwin-x86_64.tar.gz
==> Downloading from https://github-releases.githubusercontent.com/328012280/9fa20f51-dad9-47b1-aab6-6b4c0d14c5db?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AK
######################################################################## 100.0%
🍺  /usr/local/Cellar/otel-cli/0.0.6-rc2: 5 files, 12.3MB, built in 3 seconds
```

**Comment by ahayworth** [comment]
Woohoo!

Also:

> Switched to use GITHUB_TOKEN instead - is this bad? My guess is @ahayworth has a lot of tokens so has to be more careful?

Yup. 😄

**Pull request merged**
